- name: install required packages
  apt: name={{item}} state=present
  become: yes
  with_items:
    - cmake

- name: install required gems
  gem: name={{item}} state=present user_install=no
  become: yes
  with_items:
    - tmuxinator
    - homesick
